<?php
/**
 * DDE_Cliente extension for Magento
 *
 * @category   DDE
 * @package    DDE_Cliente
 * @version    1.1.0
 */
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset personal-information">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php if($this->getFormData()->getTipo() == 2): ?>Dados da Empresa<?php else: ?>Dados Pessoais<?php endif ?></h2>
            <ul class="form-list">
				<li class="wide">
					<?php echo $this->getLayout()->createBlock('cliente/customer_widget_tipo')->setTipo($this->getFormData()->getTipo())->toHtml() ?>
				</li>
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('cliente/customer_widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
            	<?php $_taxvat = $this->getLayout()->createBlock('cliente/customer_widget_taxvat') ?>
	            <?php if ($_taxvat->isEnabled()): ?>
	                <li class="fields">
						<?php echo $_taxvat->setTipo($this->getFormData()->getTipo())->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
						<?php echo $this->getLayout()->createBlock('cliente/customer_widget_rgie')->setTipo($this->getFormData()->getTipo())->setRgie($this->getFormData()->getRgie())->toHtml() ?>
					</li>
	            <?php endif ?>
                <li class="fields">
                    <div class="field telephone">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                    <div class="field fax">
                        <label for="fax">Celular</label>
                        <div class="input-box">
                            <input type="text" name="fax" id="fax" value="<?php echo $this->escapeHtml($this->getFormData()->getFax()) ?>" title="Celular" class="input-text" />
                        </div>
                    </div>
                </li>	
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                </li>
                <?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>
        </div>
        <div class="fieldset address-information">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php if($this->getFormData()->getTipo() == 2): ?><?php echo $this->__('Endereço da Empresa') ?><?php else: ?><?php echo $this->__('Seu endereço') ?><?php endif ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field zip">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field country">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>	
                <li class="fields">
					<div class="field street-address">
	                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Endereço') ?></label>
	                    <div class="input-box">
	                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Endereço') ?>" id="street_1" class="input-text required-entry" />
	                    </div>
					</div>
					<div class="field number-address">
	                    <label for="street_2" class="required"><em>*</em><?php echo $this->__('Nº') ?></label>
	                    <div class="input-box">
	                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(2)) ?>" title="<?php echo $this->__('Nº') ?>" id="street_2" class="input-text required-entry" />
	                    </div>
					</div>					
                </li>
                <li class="fields">
					<div class="field complemento">
						<label for="street_3"><?php echo $this->__('Complemento') ?></label>
	                    <div class="input-box">
	                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(3)) ?>" title="<?php echo $this->__('Complemento') ?>" id="street_3" class="input-text" />
	                    </div>
					</div>
					<div class="field bairro">
						<label for="street_4" class="required"><em>*</em><?php echo $this->__('Bairro') ?></label>
	                    <div class="input-box">
	                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(4)) ?>" title="<?php echo $this->__('Bairro') ?>" id="street_4" class="input-text required-entry" />
	                    </div>
					</div>					
                </li>
                <li class="fields">
                    <div class="field city">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" readonly />
                        </div>
                    </div>
                    <div class="field region">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;" onfocus="this.initialSelect = this.selectedIndex;" onchange="this.selectedIndex = this.initialSelect;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
        <div class="fieldset login-information">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
		var globalRegions = <?php echo $this->helper('cliente')->getRegionJson() ?>
    //]]>
    </script>
</div>
