<?php
/**
 * Trezo Cielo Payment Method
 *
 * @category   Trezo
 * @package    Trezo_Cielo
 * @author     Bruno Roeder <contato@trezo.com.br>
 *
 */
?>
<?php $info = $this->getInfo(); ?>
<div class="panel-info-cielo-boleto">
    <p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
    <p><?php echo $this->helper('trezo_cielo')->__('Order Key: %s', $info->getAdditionalInformation('order_key')) ?></p>
    <p><?php echo $this->helper('trezo_cielo')->__('Bar Code: %s', $info->getAdditionalInformation('barcode')) ?></p>
    <?php if ($info->getAdditionalInformation('boleto_url') != null) : ?>
        <p>
            <a target="_blank" href="<?php echo $info->getAdditionalInformation('boleto_url') ?>"><?php echo $this->helper('trezo_cielo')->__('click here to print the boleto.') ?></a>
        </p>
    <?php endif ?>
</div>