<div class="category-mobile-holder featured row visible-xs">
    <div class="col-xs-12">
        <div class="category-holder">
            <a href="mitsubishi/airtrek.html">
                <p>AIRTREK</p>
                <img src="<?php echo Mage::getUrl('', array('_secure'=>true)).'media/home/categories/airtrek.jpg' ?>" />
            </a>
        </div>
    </div>
    <div class="col-xs-12">
        <div class="category-holder">
            <a href="mitsubishi/outlander.html">
                <p>OUTLANDER</p>
                <img src="<?php echo Mage::getUrl('', array('_secure'=>true)).'media/home/categories/outlander.jpg' ?>" />
            </a>
        </div>
    </div>
    <div class="col-xs-12">
        <div class="category-holder">
            <a href="mitsubishi/grandis.html">
                <p>GRANDIS</p>
                <img src="<?php echo Mage::getUrl('', array('_secure'=>true)).'media/home/categories/grandis.jpg' ?>" />
            </a>
        </div>
    </div>
    <div class="col-xs-12">
        <div class="category-holder">
            <a href="mitsubishi/asx.html">
                <p>ASX</p>
                <img src="<?php echo Mage::getUrl('', array('_secure'=>true)).'media/home/categories/asx.jpg' ?>" />
            </a>
        </div>
    </div>
    <div class="col-xs-12">
        <div class="category-holder">
            <a href="mitsubishi/lancer.html">
                <p>LANCER</p>
                <img src="<?php echo Mage::getUrl('', array('_secure'=>true)).'media/home/categories/lancer.jpg' ?>" />
            </a>
        </div>
    </div>
</div>
