 <?php
	$obj 			= new Mage_Catalog_Block_Navigation();
	$store_cats = Mage::getModel('catalog/category')
					->getCollection()
					->addAttributeToSelect('*')
					// ->addFieldToFilter('level', array('eq'=> 1))
					->addFieldToFilter('level', array('eq'=> 3))
					->addFieldToFilter('is_active', array('eq' => '1'))
					->addFieldToFilter('include_in_menu', array('eq' => '1')); 
					
	// $store_cats 	= $obj->getStoreCategories();
	$current_cat    = $obj->getCurrentCategory();
	// $current_cat    = (is_object($current_cat) ? $current_cat->getName() : '');
	$currentCategoryParents = is_object($current_cat) ? $current_cat->getParentIds() : array();
	$currentCategoryParents[] =  $current_cat->getId();
?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Browse By') ?></span></strong>
    </div>
    <div class="block-content">
        <dl id="narrow-by-list2">
            <dt><?php echo $this->__('Category') ?></dt>
            <dd>
                <ol>
					<?php
						foreach ($store_cats as $cat){
							// if ($cat->getName() == $current_cat){
							if( in_array($cat->getId(), $currentCategoryParents) ){
								echo '<li class="current"><a href="'.$this->getCategoryUrl($cat).'">'.$cat->getName()."</a>\n<ol style='margin-left:20px;'>\n";
								// foreach ($obj->getCurrentChildCategories() as $subcat) {
								foreach ($cat->getChildrenCategories() as $subcat) {
									echo '<li><a href="'.$this->getCategoryUrl($subcat).'">'.$subcat->getName()."</a></li>\n";
								}
								echo "</ol>\n</li>\n";
							}else{
								echo '<li><a href="'.$this->getCategoryUrl($cat).'">'.$cat->getName()."</a></li>\n";
							}
						}
					?>
				</ol>
			</dd>
        </dl>
        <script type="text/javascript">decorateDataList('narrow-by-list2')</script>
    </div>
</div>