<?php if ($posts = $this->getRecent()): ?>
    <div class="container">
        <div class="widget-latest">
            <div class="page-title category-title center">
                <h1><?php echo Mage::helper('blog')->__('Latest Posts');  ?></h1>
            </div>
            <ul class="row">
                <?php $i = 0; ?>
                <?php foreach ($posts as $post): ?>
                    <?php if ($i<2): ?>
                        <li class="col-xs-12 col-sm-6">
                            <div class="widget-latest-wrap">
                                <div class="postContent postContent-img">
                                    <?php echo Mage::helper('cms')->getBlockTemplateProcessor()->filter($post->getShortContent()); ?>
                                </div>
                                <div class="widget-latest-content">
                                    <div class="widget-latest-title"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></div>
                                    <div class="widget-latest-details">
                                        <?php // $post->setCreatedTime($this->formatDate($post->getCreatedTime(), "long", false)); ?>
                                        <?php //echo $post->getCreatedTime(); ?>
                                        <?php $_ct= new Zend_Date($post->getCreatedTime()); ?>
                                        <span class="widget-latest-data"><!-- <i class="fa fa-clock-o"></i> --><?php echo $_ct->toString(); ?></span>
                                        <!-- <a class="widget-latest-comment" href="<?php echo $post->getAddress(); ?>#commentBox" >
                                             <i class="fa fa-comment-o"></i>
                                            <?php if ($post->getCommentCount() > 0): ?>
                                                <?php // echo $post->getCommentCount(); ?> <?php // echo Mage::helper('blog')->__('Comments'); ?>
                                            <?php endif; ?>
                                             <?php if ($post->getCommentCount() < 1): ?> 
                                                <?php echo "0"; ?> <?php // echo Mage::helper('blog')->__('Comments'); ?>
                                            <?php endif; ?>
                                        </a>
                                        <span class="postDetails-user">
                                            <i class="fa fa-user"></i>
                                            <?php echo $post->getUser(); ?>
                                        </span> -->
                                    </div>
                                    <div class="postContent postContent-desc">
                                        <?php echo Mage::helper('cms')->getBlockTemplateProcessor()->filter($post->getShortContent()); ?>
                                    </div>
                                    <a href="<?php echo $post->getAddress(); ?>"class="aw-blog-read-more all-blog"><?php echo Mage::helper('blog')->__('Read more');  ?></a>
                                </div>
                            </div>
                        </li>
                    <?php endif; ?>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </ul>
           <!-- <a href="<?php // echo $this->getBlogUrl() ?>"class="aw-blog-read-more all-blog"><?php // echo Mage::helper('blog')->__('View all posts');  ?></a> -->
        </div>
    </div>
<?php endif; ?>
<?php // $tt = count($this->getRecent()); print_r($tt) ; ?>
