<?php

$installPath = 'egoimmerce.e-goi.com';

$account = Mage::getModel('fidelitas/account')->getAccount();

if ($account->getClienteId()) {
    if (strpos($installPath, "https://") !== false) {
        $secureinstallPath = $installPath;
        $installPath = str_replace("https://", "http://", $installPath);
    }
    if (strpos($installPath, "http://") === false) {
        $installPath = "http://" . $installPath;
    }

    $secureinstallPath = str_replace("http://", "https://", $installPath);
    $last = $installPath[strlen($installPath) - 1];

    if ($last != "/") {
        $installPath .= "/";
        $secureinstallPath .= "/";
    }
    $_customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
    $listId = '';
    $subscriberId = '';
    if ($_customerId) {
        $sub = Mage::helper('fidelitas')->isCustomerSubscribed($_customerId);
        if ($sub) {
            $listId = $sub->getList();
            $subscriberId = $sub->getUid();
        }
    }

//0 Search Results
    if ($this->getRequest()->getControllerName() == 'result') {
        $nores = Mage::helper('catalogsearch')->getEngine()->getResultCollection()->addSearchFilter(Mage::helper('catalogsearch')->getQuery()->getQueryText())->getSize();
    }
    ?>

    <!-- EGOIMMERCE TRACKING CODE -->
    <script type="text/javascript">
        var _egoiaq = _egoiaq || [];
        (function () {
            var u = (("https:" == document.location.protocol) ? "<?php echo $secureinstallPath ?>" : "<?php echo $installPath ?>");
            _egoiaq.push(['setClientId', "<?php echo $account->getClienteId() ?>"]);
            _egoiaq.push(['setSubscriber', "<?php echo $subscriberId; ?>"]);
            _egoiaq.push(['setListId', "<?php echo $listId; ?>"]);
            _egoiaq.push(['setTrackerUrl', u + 'collect']);
            <?php echo $this->_getEcommerceCartUpdate() ?>
            <?php echo $this->_getOrdersTrackingCode() ?>
            <?php echo $this->_getProductPageview() ?>
            <?php echo $this->_getCategoryPageview() ?>
            <?php if (isset($nores)) {
            ?>
            var searchCount = <?php echo $nores; ?>;
            _egoiaq.push(['setCustomUrl', document.URL + '&search_count=' + searchCount]);
            <?php } ?>
            <?php
            //404 tracking
            $action = Mage::app()->getRequest()->getActionName();
            if ($action == 'noRoute') {
            ?>
            _egoiaq.push(['setDocumentTitle', '404/URL = ' + String(document.location.pathname + document.location.search).replace(/\//g, "%2f") + '/From = ' + String(document.referrer).replace(/\//g, "%2f")]);
            <?php }else{ ?>
                _egoiaq.push(['setDocumentTitle', String(document.location.pathname + document.location.search).replace(/\//g, "%2f") + '/From = ' + String(document.referrer).replace(/\//g, "%2f")]);
            <?php } ?>
            <?php echo "\n"; ?>
            _egoiaq.push(['trackPageView']);
            _egoiaq.push(['enableLinkTracking']);
            var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
            g.type = 'text/javascript';
            g.defer = true;
            g.async = true;
            g.src = u + 'egoimmerce.js';
            s.parentNode.insertBefore(g, s);
        })();
    </script>
    <!-- END EGOIMMERCE TRACKING CODE -->
    <?php
}
