<div class="category-mobile-holder featured row visible-xs">
    <div class="col-xs-12">
        <div class="category-holder">
            <a href="mitsubishi/l200-gl-gls-sport-hpe.html">
                <p>L200 GL, GLS E SPORT</p>
                <img src="<?php echo Mage::getUrl('', array('_secure'=>true)).'media/home/categories/l200-gl-gls-sport.jpg' ?>" />
            </a>
        </div>
    </div>
    <div class="col-xs-12">
        <div class="category-holder">
            <a href="mitsubishi/l200-triton-dakar.html">
                <p>L200 TRITON E DAKAR</p>
                <img src="<?php echo Mage::getUrl('', array('_secure'=>true)).'media/home/categories/l200-triton-dakar.jpg' ?>" />
            </a>
        </div>
    </div>
    <div class="col-xs-12">
        <div class="category-holder">
            <a href="mitsubishi/pajero-sport-full.html">
                <p>PAJERO SPORT E FULL</p>
                <img src="<?php echo Mage::getUrl('', array('_secure'=>true)).'media/home/categories/pajero-sport-full.jpg' ?>" />
            </a>
        </div>
    </div>
    <div class="col-xs-12">
        <div class="category-holder">
            <a href="mitsubishi/pajero-tr4-io.html">
                <p>PAJERO TR4 E IO</p>
                <img src="<?php echo Mage::getUrl('', array('_secure'=>true)).'media/home/categories/pajero-tr4-io.jpg' ?>" />
            </a>
        </div>
    </div>
</div>
