<?php $additionaldata = unserialize($this->getInfo()->getData('additional_data')); ?>
<?php $parcelas = isset($additionaldata["cc_parcelas"]) ? $additionaldata["cc_parcelas"] : '' ?>
<?php $status = isset($additionaldata["status"]) ? $additionaldata["status"] : '' ?>
<?php if(isset($additionaldata["autorizacao"])){
	$autorizacao = $this->__('Mensagem da transação: (%s) %s', $additionaldata["autorizacao"]['codigo'], $additionaldata["autorizacao"]['mensagem']);
}else{
	$autorizacao = "";
} ?>
<?php if(isset($additionaldata["captura"])){
	$captura = $additionaldata["captura"]['mensagem'];
}else{
	$captura = "";
} ?>

<p><?php echo $this->__('Name on the Card: %s', $this->htmlEscape($this->getInfo()->getCcOwner())) ?></p>
<p><?php echo $this->__('Credit Card Type: %s', $this->htmlEscape($this->getCcTypeName())) ?></p>
<p><?php echo $this->__('Credit Card Number: xxxx-%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?></p>
<p><?php echo $this->__('Expiration Date: %s/%s', $this->htmlEscape($this->getCcExpMonth()), $this->htmlEscape($this->getInfo()->getCcExpYear())) ?></p>
<p><?php echo $this->__('Número de Parcelas: %s', $parcelas) ?></p>
<?php if(isset($additionaldata["tid"])): ?>
	<?php if($additionaldata["tid"]): ?>
	<p><?php echo $this->__('Código da transação: %s', $additionaldata["tid"]) ?></p>
	<?php endif ?>
	<?php if(isset($additionaldata["erro"])): ?>
	<p><?php echo $this->__('Mensagem da transação: (%s) %s', $additionaldata["erro"]['codigo'], $additionaldata["erro"]['mensagem']) ?></p>
	<?php elseif(isset($additionaldata["autorizacao"])): ?>
	<p style="font-weight: bold; color: <?php echo ($status == 4 || $status == 6) ? '#056840' : '#FF0400' ?>"><?php echo $autorizacao ?>
	<?php if(!$captura): ?>
		<span style="color: #000"> | <a href="#" onclick="window.open('<?php echo Mage::getUrl('cielo/standard/captura', array('order_id' => $this->getOrder()->getId())) ?>', 'captura', 'width=400,height=400');">Clique aqui para capturar</a></span>
	<?php endif ?>
	</p>
	<?php endif ?>
<?php if($captura): ?>
<p><b><?php echo $captura ?></b></p>
<?php endif ?>
<?php endif ?>
<?php echo Mage::getSingleton('core/layout')->createBlock('cielo/risco')->toHtml() ?>
