<?php
/**
 * Trezo Cielo Payment Method
 *
 * @category   Trezo
 * @package    Trezo_Cielo
 * @author     Bruno Roeder <contato@trezo.com.br>
 *
 */
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list cielo-boleto-payment-icons" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <?php if ($instructions = $this->getInstructions()) : ?>
            <li>
                <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content">
                    <?php echo nl2br($instructions) ?>
                </div>
            </li>
    <?php endif; ?>
</ul>

