<?php
$trustvoxId = Mage::helper('hibridotrustvox')->getTrustvoxId( Mage::app()->getStore()->getId() );
?>
<script type="text/javascript" async="true" src="//rate.trustvox.com.br/widget.js"></script>
<script type="text/javascript">
var _trustvox_shelf_rate = _trustvox_shelf_rate || [];
_trustvox_shelf_rate.push(['_storeId', '<?php echo $trustvoxId;?>']);
</script>
<script src="//certificate.trustvox.com.br/widget.js"></script>
